### ISSUE TITLE
Do we need to go down the tibble tangent?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#394]
There was some confusion about why tibbles are important.

Can't most of the tidyverse functions use data frames? Do we need to explain `tibble` beforehand?

if we did something like 
```
library(dplyr)
rename(iris, spp = Species)
```
It should work fine.

Maybe we should address tibbles when they appear for the first time. "we can see it's now a fancy data frame called a tibble, which has some nice formatting"

It might be nice to not use an example like `mtcars` because most stuff we read in from csv or delimited files don't have row names.

**Comment by carriewright11** [comment]
yeah that's the reason I used mtcars actually  - was to show that you would lose rownames - since I often had data with rownames back in the day. But we could just not discuss them and basically have one slide that says you will see tibbles and dataframes and they are very similar and not say why they are different? I feel like if we  say how they are different then people will want to know how you make them etc? I thought they might have colleagues not using tibbles and it might be of benefit but for the sake of time we can cut this.

**Comment by carriewright11** [comment]
square and rectangle slide and that's it
