### ISSUE TITLE
Subsetting

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#396]
- [x] show slice_sample()  emphasize is random
- [x] show skimr install
- [x] rename example with multiple columns
- [x] talk about janitor
- [x] for janitor or otherwise... "column 1", "column 2", "column 3" > "column_1", "column_2", "column_3"

Lab
- [x] tell them to nest or make a temporary objects for part 3 question 1
- [x]  maybe reverse the question order? this group had a harder time... could do question 2 first and then question 1
- [x] remove some of part two questions?
- [x] maybe tell them that it will cause an error in question 2b - so they don't stress
- [x] number 3- add hint about `desc` and tell them to do it in descending arrangement
- [x] Make it WT+2 instead of WT^2

**Comment by avahoffman** [comment]
Upon rewatching the recording, students were pretty confused about slide 20/98 where a data frame is converted to a tibble. I think we should probably use a different example to introduce tibbles where the row names aren't lost, since they kind of got hung up on why the rownames were disappearing. I do think it's an important concept, but perhaps separate "dataframe vs tibble" from "rownames to column"?

**Comment by carriewright11** [comment]
sure, we can separate them
