### ISSUE TITLE
Can we make the gender example more inclusive? Or just another example altogether? Don't want anyone to feel called out

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#415]

**Comment by carriewright11** [comment]
yeah I actually made this initially as a version to show a better dataset - because even  Other isn't sadly  an option in so many gov datasets. Happy to do either here  either make it super good with lots of options. But that might make the data a bit complicated for the example - so we can try to think of something else to recode

**Comment by carriewright11** [comment]
We could show a good example of gender coded data on slack or something ? Know of any good datasets like that?
