### ISSUE TITLE
Places where fake data is made, can we make a jhur version?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#416]
Can read in some data even if it's tiny, kinda like https://github.com/jhudsl/intro_to_r/blob/main/data/asthma.xlsx

I think it is good for people to practice.

**Comment by carriewright11** [comment]
I have an issue to add it to jhur but. just haven't been able to get to it yet. It sounds like you would prefer to read an excel file - is that correct?

**Comment by avahoffman** [comment]
Could also be a csv file. just not data generated  within R.

**Comment by carriewright11** [comment]
Here are the current datasets just to help know what we are working with:
- Fake data: There are a couple of slides with this vector (0,Na, -1) to show all the different kinds of NA, NAN, and Inf options when we divide the vector by 0
- Real data: we use the `bike` dataset from JHUR and we now read it in instead of just loading it
- Real data: we use the `airquality` dataset which was a great one for my `NA` needs. 
- Fake data: I used one fake dataset for the recoding - so I could make a very messy example - in making it we recap how to use `rep` and `seq`

I can copy recoding dataset to our website - I can do it as an excel

**Comment by carriewright11** [comment]
also I show a fairly complicated data import now for subsetting
