### ISSUE TITLE
Reproducibility thoughts

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#467]
- [ ] I wonder if it's worth starting with an Excel example? Demonstrating how it's difficult to point-and-click your way to the same result if you're working in that kind of interface.
- [x] @carriewright11 @clifmckee thoughts on swapping basic R and Reproducibility? I feel like there were some things that were mentioned that would benefit from running some code chunks, seeing what a vector is, etc.

**Comment by carriewright11** [comment]
Love the new concepts in the lab! Had some thoughts to help prepare students for it:

Lecture
- [ ] maybe add a slide about comments to differentiate the use of `#`
- [ ] Adding a slide on  `sessionInfo()` would help prepare students for the lab
- [ ] Adding a slide on `set.seed()` would also be helpful for the lab
- [ ] Might want to add those to a cheatsheet?

Lab
- [ ] For students trying on their own,  it might be useful to add the first chunk - since we haven't gone over assignments yet (or swap it out with basic R in the order like Ava suggested)

**Comment by avahoffman** [comment]
We also got some feedback that day 1 was a bit high level, and they wanted to dive into the code in more detail, which also might be a good reason to swap reproducibility and basic R
