### ISSUE TITLE
add videos from last class?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#64]
Do we want to add the lectures from the summer to the website?

**Comment by avahoffman** [comment]
I have them downloaded - question is, where do we want them. YouTube? DaSL Google Drive?

**Comment by carriewright11** [comment]
hmm good question, if we want to be consistent... then John posted them on YouTube with his own channel I think... we could make a jhudsl channel - I don't think that exists yet, right? I know @cansavvy made an ITN channel. However I imagine just putting them on the google drive would be easier? That seems fine with me. It also depends on how "public" we want the lectures to be. I feel like since people sometimes asked questions, maybe it is better on google drive? in case they don't want to be on YouTube? idk what dp you think?

**Comment by cansavvy** [comment]
I can also see an argument for Venmo. Allows for a bit more control over who views it and no ads. But would require us to get a subscription -- might make sense to get one for jhudsl. Also won't use up room in a google drive. 

But perhaps short term a google drive is fine.

**Comment by avahoffman** [comment]
I like google drive for the "raw" lectures from last year. I'd love to get the CTL folks to help us edit and record some official lectures for Youtube since that's more public facing. Probably shouldn't have students on Youtube.

If we upload to the drive link Fred provided, it won't use up any one user's space. I'll plan to do that for now.

**Comment by carriewright11** [comment]
woohoo done! Yay @avahoffman!
